# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: macos-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/amd64
        goos: [darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - name: "Golang env"
        run: |
          wget --progress=dot:mega -O go-linux.tar.gz https://golang.org/dl/go1.16.5.darwin-amd64.tar.gz &&
          mkdir -p $HOME/go1.16 && tar -C $HOME/go1.16 -xzf go-linux.tar.gz &&
          mkdir -p $HOME/go/bin $HOME/go/src $HOME/go/pkg &&
          export GO_HOME=$HOME/go1.16/go &&
          export GOPATH=$HOME/go &&
          export PATH=${GOPATH}/bin:${GO_HOME}/bin/:$PATH &&
          go version

      - name: "Build"
        run: |
          export GO_HOME=$HOME/go1.16/go &&
          export GOPATH=$HOME/go &&
          export PATH=${GOPATH}/bin:${GO_HOME}/bin/:$PATH &&
          go version &&
          cd cmd/tap-over-https-gui &&
          go build &&
          tar zcvf tap-over-https-gui-$(basename ${GITHUB_REF})-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz tap-over-https-gui &&
          ls -lh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tap-over-https-gui-${GITHUB_REF}-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
